import * as THREE from 'three';
import { OrbitControls } from 'three/examples/jsm/controls/OrbitControls.js';
const { buildMilkyWay } = await import('./scene/galaxy.js?v=20260915-9');
const { buildSolarSystem } = await import('./scene/solar.js?v=20260915-5');

const root = document.getElementById('space');
const loader = document.getElementById('loader');
const objectCard = document.getElementById('object-card');
const objectTitle = document.getElementById('object-title');
const objectKicker = document.getElementById('object-kicker');
const objectDescription = document.getElementById('object-description');
const objectMeta = document.getElementById('object-meta');
const toast = document.getElementById('toast');
const simTime = document.getElementById('sim-time');
const lowPower = matchMedia('(max-width: 700px)').matches || (navigator.hardwareConcurrency || 8) <= 4;
const scene = new THREE.Scene();
scene.background = new THREE.Color(0x03050a);
const camera = new THREE.PerspectiveCamera(52, innerWidth / innerHeight, .04, 10000);
camera.position.set(14, 9, 26);
const renderer = new THREE.WebGLRenderer({ antialias: !lowPower, powerPreference: 'high-performance' });
renderer.setPixelRatio(Math.min(devicePixelRatio || 1, lowPower ? 1.25 : 1.8)); renderer.setSize(innerWidth, innerHeight); renderer.outputColorSpace = THREE.SRGBColorSpace; renderer.toneMapping = THREE.ACESFilmicToneMapping; renderer.toneMappingExposure = 1.15; root.appendChild(renderer.domElement);
const controls = new OrbitControls(camera, renderer.domElement); controls.enableDamping=true; controls.dampingFactor=.045; controls.enablePan=true; controls.screenSpacePanning=true; controls.rotateSpeed=.55; controls.zoomSpeed=.8; controls.minDistance=1.2; controls.maxDistance=3600; if('zoomToCursor'in controls)controls.zoomToCursor=true;
scene.add(new THREE.HemisphereLight(0x7d8eb7,0x02030a,.38)); const rim=new THREE.DirectionalLight(0x9ebdff,.46);rim.position.set(12,20,18);scene.add(rim);
function makeStars(count,radius,color,size,opacity){const p=new Float32Array(count*3);let s=12345+count;const r=()=>{s=(s*1664525+1013904223)>>>0;return s/4294967296};for(let i=0;i<count;i++){const rr=radius*(.5+r()*.5),a=r()*Math.PI*2,z=(r()*2-1)*rr,xy=Math.sqrt(Math.max(0,rr*rr-z*z));p[i*3]=Math.cos(a)*xy;p[i*3+1]=z;p[i*3+2]=Math.sin(a)*xy}const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.BufferAttribute(p,3));return new THREE.Points(g,new THREE.PointsMaterial({color,size,transparent:true,opacity,depthWrite:false,blending:THREE.AdditiveBlending}))}
const bg=new THREE.Group();bg.add(makeStars(lowPower?5000:14000,3100,0xcfe0ff,lowPower?.65:.85,.82));bg.add(makeStars(lowPower?900:2400,2500,0xffc88f,lowPower?.7:.9,.4));scene.add(bg);
const galaxy=buildMilkyWay(lowPower);scene.add(galaxy);const solar=buildSolarSystem(lowPower);const solarAnchor=new THREE.Group();solarAnchor.position.copy(galaxy.userData.solarNeighborhood||new THREE.Vector3(0,0,470));solarAnchor.add(solar);galaxy.add(solarAnchor);
const core=new THREE.Group();const coreMesh=new THREE.Mesh(new THREE.SphereGeometry(2.2,32,20),new THREE.MeshBasicMaterial({color:0xffffff}));core.add(coreMesh);const coreGlow=new THREE.Mesh(new THREE.SphereGeometry(3.8,24,16),new THREE.MeshBasicMaterial({color:0x6faeff,transparent:true,opacity:.1,blending:THREE.AdditiveBlending,depthWrite:false}));core.add(coreGlow);solar.add(core);
const orbitItems=[];const labels=['PROJECTS','EXPERIMENTS','IDEAS','NOTES','ABOUT','ARCHIVE'];const colors=[0x6fb6ff,0x8ef0d0,0xffbf77,0xd2a5ff,0xf2edf0,0x93a9c8];const rnObjects=[];labels.forEach((label,i)=>{const orbit=new THREE.Group();const d=7+i*.7;orbit.rotation.y=i/6*Math.PI*2;const a=new THREE.Group();a.position.x=d;orbit.add(a);const mesh=new THREE.Mesh(new THREE.SphereGeometry(.72,24,16),new THREE.MeshStandardMaterial({color:colors[i],emissive:colors[i],emissiveIntensity:.18,roughness:.42}));a.add(mesh);for(let m=0;m<2;m++){const p=new THREE.Group();const moon=new THREE.Mesh(new THREE.SphereGeometry(.11,12,8),new THREE.MeshBasicMaterial({color:colors[i]}));moon.position.x=1.2+m*.45;p.add(moon);a.add(p);orbitItems.push({pivot:p,speed:.02+m*.01})}const pts=[];for(let j=0;j<=120;j++){const t=j/120*Math.PI*2;pts.push(new THREE.Vector3(Math.cos(t)*d,0,Math.sin(t)*d))}orbit.add(new THREE.LineLoop(new THREE.BufferGeometry().setFromPoints(pts),new THREE.LineBasicMaterial({color:0x7184a6,transparent:true,opacity:.16,depthWrite:false})));core.add(orbit);rnObjects.push({label,title:label,description:`${label} in the RN working universe.`,meta:`RN SYSTEM · ${label}`});orbitItems.push({object:mesh,data:rnObjects[i]})});
let selected=null,motion=true,rate=1,t=0,free=false;const ray=new THREE.Raycaster(),pointer=new THREE.Vector2(),clock=new THREE.Clock(),keys={w:0,a:0,s:0,d:0,q:0,e:0};let shift=0;
function pick(e){const r=renderer.domElement.getBoundingClientRect();pointer.x=((e.clientX-r.left)/r.width)*2-1;pointer.y=-((e.clientY-r.top)/r.height)*2+1;ray.setFromCamera(pointer,camera);return ray.intersectObjects(orbitItems.filter(x=>x.object).map(x=>x.object),true)[0]?.object}
function showObject(data){selected=data;objectKicker.textContent=data.meta;objectTitle.textContent=data.title;objectDescription.textContent=data.description;objectMeta.textContent='FLY TO OBJECT · DRAG TO ORBIT · WHEEL TO ZOOM';objectCard.classList.remove('hidden')}
renderer.domElement.addEventListener('pointerup',e=>{if(free)return;const hit=pick(e);const item=orbitItems.find(x=>x.object===hit);if(item)showObject(item.data)});
document.getElementById('object-close').onclick=()=>objectCard.classList.add('hidden');
document.getElementById('object-fly').onclick=()=>{if(!selected)return;const item=orbitItems.find(x=>x.data===selected);if(!item)return;const target=item.object.getWorldPosition(new THREE.Vector3());const from=camera.position.clone(),ft=controls.target.clone(),to=target.clone().add(new THREE.Vector3(5,2.7,8)),start=performance.now();const step=n=>{const p=Math.min(1,(n-start)/950),e=p<.5?4*p*p*p:1-Math.pow(-2*p+2,3)/2;camera.position.lerpVectors(from,to,e);controls.target.lerpVectors(ft,target,e);if(p<1)requestAnimationFrame(step);};requestAnimationFrame(step)};
document.querySelectorAll('[data-destination]').forEach(b=>b.onclick=()=>{const k=b.dataset.destination;document.getElementById('destination-panel').classList.add('hidden');if(k==='galaxy'){camera.position.set(0,210,1040);controls.target.set(0,0,0)}else if(k==='solar'){const p=solarAnchor.getWorldPosition(new THREE.Vector3());camera.position.copy(p.clone().add(new THREE.Vector3(0,72,250)));controls.target.copy(p)}else{camera.position.set(0,8,21);controls.target.set(0,0,0)}controls.update()});
document.querySelectorAll('[data-tool]').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tool').forEach(x=>x.classList.remove('active'));b.classList.add('active');const k=b.dataset.tool;document.getElementById('destination-panel').classList.toggle('hidden',k!=='destinations');document.getElementById('visual-panel').classList.toggle('hidden',k!=='visual')});
document.getElementById('journeys').onclick=()=>showToast('RN JOURNEY · RN SYSTEM → SOLAR SYSTEM → MILKY WAY');document.getElementById('help').onclick=()=>showToast('DRAG TO ORBIT · WHEEL TO ZOOM · K FOR FREE FLY');document.getElementById('rewind').onclick=()=>rate=-Math.abs(rate);document.getElementById('forward').onclick=()=>rate=Math.abs(rate);document.getElementById('pause').onclick=()=>motion=!motion;document.querySelectorAll('.rate').forEach(b=>b.onclick=()=>{rate=Math.sign(rate||1)*Number(b.dataset.rate);document.querySelectorAll('.rate').forEach(x=>x.classList.remove('active'));b.classList.add('active')});document.getElementById('star-toggle').onchange=e=>{bg.visible=galaxy.visible=e.target.checked};document.getElementById('motion-toggle').onchange=e=>motion=e.target.checked;document.getElementById('orbit-toggle').onchange=e=>scene.traverse(o=>{if(o.isLineLoop)o.visible=e.target.checked});
function showToast(m){toast.textContent=m;toast.classList.add('visible');clearTimeout(showToast.t);showToast.t=setTimeout(()=>toast.classList.remove('visible'),2200)}
window.onkeydown=e=>{const k=e.key.toLowerCase();if(k==='k'){free=!free;controls.enabled=!free;showToast(free?'FREE FLY ON':'FREE FLY OFF')}if(k in keys)keys[k]=1;if(e.key==='Shift')shift=1};window.onkeyup=e=>{const k=e.key.toLowerCase();if(k in keys)keys[k]=0;if(e.key==='Shift')shift=0};
function freeUpdate(dt){if(!free)return;const speed=(14+(shift?45:0))*dt,d=new THREE.Vector3();camera.getWorldDirection(d);const r=new THREE.Vector3().crossVectors(d,camera.up).normalize();if(keys.w)camera.position.addScaledVector(d,speed);if(keys.s)camera.position.addScaledVector(d,-speed);if(keys.a)camera.position.addScaledVector(r,-speed);if(keys.d)camera.position.addScaledVector(r,speed);if(keys.q)camera.position.y+=speed;if(keys.e)camera.position.y-=speed}
function animate(){requestAnimationFrame(animate);const dt=Math.min(.05,clock.getDelta());if(motion){t+=dt*rate;if(solar.userData.advance)solar.userData.advance(t);if(galaxy.userData.advance)galaxy.userData.advance(t,dt);core.rotation.y=t*.05;coreGlow.scale.setScalar(1+Math.sin(t*1.7)*.04);orbitItems.forEach(x=>{if(x.pivot)x.pivot.rotation.y+=x.speed});}bg.rotation.y+=dt*.0005*(motion?1:0);freeUpdate(dt);if(!free)controls.update();simTime.textContent=rate===1?'RIGHT NOW':`${Math.abs(rate)}× SIMULATION`;renderer.render(scene,camera)}
addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});loader.classList.add('hidden');showToast('RN UNIVERSE READY');animate();